"""empty message

Revision ID: 1aac4fa985f0
Revises: 
Create Date: 2020-10-09 16:36:52.647686

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1aac4fa985f0'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('Artist',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name_artist', sa.String(), nullable=False),
    sa.Column('city', sa.String(length=120), nullable=False),
    sa.Column('state_artist', sa.String(length=120), nullable=False),
    sa.Column('phone', sa.String(length=120), nullable=False),
    sa.Column('website', sa.String(length=120), nullable=True),
    sa.Column('seeking_talent', sa.Boolean(), nullable=True),
    sa.Column('image_link', sa.String(length=500), nullable=True),
    sa.Column('seeking_description', sa.String(), nullable=True),
    sa.Column('facebook_link', sa.String(length=120), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('Venue',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name_venue', sa.String(), nullable=False),
    sa.Column('city', sa.String(length=120), nullable=False),
    sa.Column('state_venue', sa.String(length=120), nullable=False),
    sa.Column('address', sa.String(length=120), nullable=False),
    sa.Column('phone', sa.String(length=120), nullable=False),
    sa.Column('image_link', sa.String(length=500), nullable=True),
    sa.Column('website', sa.String(length=120), nullable=True),
    sa.Column('seeking_talent', sa.Boolean(), nullable=True),
    sa.Column('facebook_link', sa.String(length=120), nullable=False),
    sa.Column('seeking_description', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('ArtistGenres',
    sa.Column('genres_id', sa.Integer(), nullable=False),
    sa.Column('genres', sa.String(), nullable=False),
    sa.Column('artist_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['artist_id'], ['Artist.id'], ),
    sa.PrimaryKeyConstraint('genres_id')
    )
    op.create_table('Show',
    sa.Column('id_show', sa.Integer(), nullable=False),
    sa.Column('Venue_Id', sa.Integer(), nullable=False),
    sa.Column('Artist_Id', sa.Integer(), nullable=False),
    sa.Column('Date', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['Artist_Id'], ['Artist.id'], ),
    sa.ForeignKeyConstraint(['Venue_Id'], ['Venue.id'], ),
    sa.PrimaryKeyConstraint('id_show')
    )
    op.create_table('VenueGenres',
    sa.Column('genres_id', sa.Integer(), nullable=False),
    sa.Column('genres', sa.String(), nullable=False),
    sa.Column('Venue_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['Venue_id'], ['Venue.id'], ),
    sa.PrimaryKeyConstraint('genres_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('VenueGenres')
    op.drop_table('Show')
    op.drop_table('ArtistGenres')
    op.drop_table('Venue')
    op.drop_table('Artist')
    # ### end Alembic commands ###
