"""empty message

Revision ID: a4ea0e920fb3
Revises: 1aac4fa985f0
Create Date: 2020-10-09 17:12:29.480479

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a4ea0e920fb3'
down_revision = '1aac4fa985f0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('Artist', sa.Column('name', sa.String(), nullable=False))
    op.add_column('Artist', sa.Column('state', sa.String(length=120), nullable=False))
    op.drop_column('Artist', 'name_artist')
    op.drop_column('Artist', 'state_artist')
    op.add_column('Venue', sa.Column('name', sa.String(), nullable=False))
    op.add_column('Venue', sa.Column('state', sa.String(length=120), nullable=False))
    op.drop_column('Venue', 'name_venue')
    op.drop_column('Venue', 'state_venue')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('Venue', sa.Column('state_venue', sa.VARCHAR(length=120), autoincrement=False, nullable=False))
    op.add_column('Venue', sa.Column('name_venue', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.drop_column('Venue', 'state')
    op.drop_column('Venue', 'name')
    op.add_column('Artist', sa.Column('state_artist', sa.VARCHAR(length=120), autoincrement=False, nullable=False))
    op.add_column('Artist', sa.Column('name_artist', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.drop_column('Artist', 'state')
    op.drop_column('Artist', 'name')
    # ### end Alembic commands ###
